### ISSUE TITLE
Trident support

### ISSUE THREAD

**Issue by nmoinvaz** [arv/ExplorerCanvas#13]
It appears that the script fails to load when using Trident/IE web browser control. The errors occurs at https://github.com/arv/ExplorerCanvas/blob/aa989ea9d9bac748638f7c66b0fc88e619715da6/excanvas.js#L51

In Trident, MSIE is not defined in the user agent and the return value for the match function is null. I'm not sure the IE_VERSION variable is used anywhere and maybe it can be removed.

**Comment by arv** [comment]
Doesn't look like it is being used anywhere.

Patches welcome

**Comment by nmoinvaz** [comment]
Looks like there was an issue with the pull request. I have corrected it.
